export const chatSocketSagaHandlers = {
  USER_CHAT_INVITATION_WORKER: 'USER_CHAT_INVITATION_WORKER',
  ROOM_MESSAGE_NOTIFICATION_WORKER: 'ROOM_MESSAGE_NOTIFICATION_WORKER',
  ROOM_MESSAGE_LIST_WORKER: 'ROOM_MESSAGE_LIST_WORKER',
} as const;
