export const strings = {
  emailHolder: 'Your email',
  passwordHolder: 'Password',
  reset: 'Reset',
  createYourAccount: 'Create Your Safe Space',
  enterSafePlace: 'Enter to Your Safe Place',
  enterWithGoogle: 'Enter with Google',
  enterWithOutlook: 'Enter with Outlook',
  register: 'Register',
  login: 'Log In',
  or: 'or',
  useYourEmail: 'Use your email to access encryption page',
  alreadyHaveAccount: 'Already have an account?',
  welcomeBack: 'Welcome back',
  dontHaveAccount: "Don't have an account?",
  continue: 'Continue',
  forgotYourPassword: 'Forgot Your Password?',
};
