export const strings = {
  emailHolder: 'Your email',
  passwordHolder: 'Password',
  reset: 'Reset',
  secureSpace: 'Secure Space',
  enterAccount: 'Enter to Your Account',
  enterWithGoogle: 'Enter with Google',
  enterWithOutlook: 'Enter with Outlook',
  register: 'Register',
  or: 'or',
  useYourEmail: 'Use your email to access encryption page',
  alreadyHaveAccount: 'Already have an account?',
  welcomeBack: 'Welcome back',
  dontHaveAccount: "You don't have an account yet!",
  pleaseSignUp: 'Please Sign Up',
  continue: 'Continue',
  forgotYourPassword: 'Forgot Your Password?',
  signUp: 'Sign Up',
  logIn: 'Log In',
};
