export const strings = {
  nik: 'Name',
  imergencyPasswords: 'Imergency Passwords',
  savePasswords: 'Save passwords',
  savePlace: 'Save place',
  accountData: 'Add Your account data',
  yourNik: 'Add Your name',
  nikPlaceholder: 'TransparentCowboy',
  imergencyPasswordPlaceholder: 'Imergency password',
  imergencyEmailPlaceholder: 'Imergency email',
  securePlace: 'Add Your first secure place',
  placeName: 'Place name',
  address: 'Select address',
  delete: 'Delete',
  radius: 'Radius in meters',
  welcomeAboard: 'Welcome on board!',
  allmostDone: 'Allmost Done',
  pleaseSaveYourKey:
    'Download and store your key safe, to be able restore or use your encrypted data with other devices',
  saveYourKey: 'Save Your Key',
  yourKeyPassword: 'Password',
  confirmKeyPassword: 'Confirm Password',
  nowYouCanStart: 'Now you can start saving your confidential content!',
  toTheMainScreen: 'To the main screen',
  saveNikname: 'Save nikname',
  nikIncorrect: 'Name value is incorrect',
  mister: 'Mr.',
  missis: 'Ms.',
  other: 'Other',
  addingPlaceError: 'Adding place error',
};
