export const strings = {
  nikSex: 'Nik & Sex',
  imergencyPasswords: 'Imergency Passwords',
  savePasswords: 'Save passwords',
  savePlace: 'Save place',
  accountData: 'Add Your account data',
  yourSex: 'Choose Your sex',
  yourNik: 'Add Your nik',
  nikPlaceholder: 'TransparentCowboy',
  passwordPlaceholder: 'Password',
  securePlace: 'Add Your first secure place',
  placeName: 'Place name',
  address: 'Select address',
  delete: 'Delete',
  radius: 'Radius',
  welcomeAboard: 'Welcome aboard!',
  nowYouCanStart: 'Now you can start saving your confidential content!',
  toTheMainScreen: 'To the main screen',
  saveNikname: 'Save nikname',
  nikIncorrect: 'Nik value is incorrect',
  // phoneHolder: '+xxxxxxxxxxxx',
  // youRegistered: 'You registered!',
  // protectYourShelter: 'Protect Your Shelter, add secure settings',
  // hereInitialSecure: 'Here You can set your initial secure presets',
  // confirmYourDevice: 'Confirm Your device',
  // confirmPhoneNumber: 'Confirm Your phone number (optional)',
  // addImergencyPassword:
  //   'Add Your first, second and third password for the imergency case',
  // addYourPlaces: 'Add your confident places',
};
