export const strings = {
  connectedChatServer: 'Connected to the chat server',
  connectedChatWithId: 'Connected to the chat with ID:',
  disconnectedChatWithId: 'Disconnected from the chat with ID:',
  newMessageReceived: 'New message received:',
  newRoomMessageReceived: 'New in-room message received:',
  disconnectedChatServer: 'Disconnected from the chat server',
  socketError: 'Socket error:',
  socketIsNotConnected: 'Socket is not connected',
  joinedChatRoom: 'Joined chat room:',
  userChatInvitation: 'User chat invitation',
  newRoomInvitation: 'You have been invited to a new chat room:',
  findRoomInChatList: 'You could find it in the chat list',
  chatInvitationDeclined: 'Invitation Declined',
  chatInvitationAccepted: 'Invitation Accepted',
  messageDisplayError: 'Messages display error',
  errorLeavingChatRoom: 'Error leaving chat room:',
  enterYourMessage: 'Enter your message',
  chatRoomNotFound: 'Chat room not found',
  errorDeletingChatRoom: 'Error deleting chat room:',
  noPrivateChatKeyFound:
    "Can't decrypt the messages. No private chat key found",
  errorJoiningChatRoom: 'Error joining chat room:',
  userJoinedChatWithId: 'User joined the chat. Interlocutor ID:',
  userLeftChatWithId: 'User left the chat. Interlocutor ID:',
};
