export const strings = {
  connectedChatServer: 'Connected to the chat server',
  connectedChatWithId: 'Connected to the chat with ID:',
  disconnectedChatWithId: 'Disconnected from the chat with ID:',
  newMessageReceived: 'New message received:',
  newRoomMessageReceived: 'New in-room message received:',
  disconnectedChatServer: 'Disconnected from the chat server',
  socketError: 'Socket error:',
  socketIsNotConnected: 'Socket is not connected',
  joinedChatRoom: 'Joined chat room:',
  userChatInvitation: 'User chat invitation',
  newRoomInvitation: 'You have been invited to a new chat room:',
  findRoomInChatList: 'You could find it in the chat list',
  chatInvitationDeclined: 'Invitation Declined',
  chatInvitationAccepted: 'Invitation Accepted',
  errorFetchingMessages: 'Error fetching messages:',
};
