export const strings = {
  emailHolder: 'Your Email',
  passwordHolder: 'Password',
  reset: 'Reset',
  secureSpace: 'Secure Space',
  enterAccount: 'Sign in to Your Account',
  enterWithGoogle: 'Sign in with Google',
  enterWithOutlook: 'Sign in with Outlook',
  register: 'Register',
  or: 'or',
  useYourEmail: 'Use your email to access the encryption page',
  alreadyHaveAccount: 'Already have an account?',
  welcomeBack: 'Welcome back',
  dontHaveAccount: "Don't have an account yet?",
  pleaseSignUp: 'Please sign up',
  confirmYourEmail: 'Confirm Your Email',
  emailLinkSent: 'A confirmation link has been sent to your mailbox',
  emailLinkPrevioslySent: 'Please check your mailbox os Sign Up again',
  continue: 'Continue',
  forgotYourPassword: 'Forgot your password?',
  signUp: 'Sign Up',
  logIn: 'Log In',
  tooShort: 'Too Short!',
  tooLong: 'Too Long!',
  required: 'Required',
  invalidEmail: 'Invalid email',
};
